version: "3"

services:
  web:
    # image: node:18-alpine
    build: .
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST:-example.com}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    restart: always
    # ports:
    #   - "${WEB_PORT:-80}:3000"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy-compose_default
